CREATE TABLE [dbo].[AccountDeviceTokens]
(
	[DeviceTokenId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AccountId] BIGINT NOT NULL FOREIGN KEY REFERENCES ACCOUNTS(AccountId),
	OS NVARCHAR(10) NOT NULL,
	DeviceToken NVARCHAR(500) NOT NULL
)
