CREATE TABLE [dbo].[AccountDevicePins]
(
	[PinId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	AccountId BIGINT NOT NULL FOREIGN KEY REFERENCES Accounts(AccountId),
	DeviceId BIGINT NOT NULL FOREIGN KEY REFERENCES Devices(DeviceId),
	PIN NVARCHAR(15) NOT NULL
)
