CREATE TABLE [dbo].[AuditLog]
(
	[AuditLogId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ActorAccountId BIGINT NOT NULL FOREIGN KEY REFERENCES Accounts(AccountId),
	[Action] NVARCHAR(50) NOT NULL,
	TargetType NVARCHAR(30) NOT NULL,
	TargetId BIGINT NULL,
	Details NVARCHAR(400) NULL,
	CreatedDateTime DATETIME NOT NULL
)
