//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tausend.RelayServer.DeviceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://Tausend.Wearelomo.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tausend.RelayServer.DeviceService.DeviceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tausend.RelayServer.DeviceService.DeletedDeviceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tausend.RelayServer.DeviceService.UpdateDeviceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tausend.RelayServer.DeviceService.CreatedDeviceResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tausend.RelayServer.DeviceService.ResponseStates StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tausend.RelayServer.DeviceService.ResponseStates State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceResponse", Namespace="http://Tausend.Wearelomo.com")]
    [System.SerializableAttribute()]
    public partial class DeviceResponse : Tausend.RelayServer.DeviceService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tausend.RelayServer.DeviceService.Device DeviceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tausend.RelayServer.DeviceService.Device Device {
            get {
                return this.DeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceField, value) != true)) {
                    this.DeviceField = value;
                    this.RaisePropertyChanged("Device");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletedDeviceResponse", Namespace="http://Tausend.Wearelomo.com")]
    [System.SerializableAttribute()]
    public partial class DeletedDeviceResponse : Tausend.RelayServer.DeviceService.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDeviceResponse", Namespace="http://Tausend.Wearelomo.com")]
    [System.SerializableAttribute()]
    public partial class UpdateDeviceResponse : Tausend.RelayServer.DeviceService.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreatedDeviceResponse", Namespace="http://Tausend.Wearelomo.com")]
    [System.SerializableAttribute()]
    public partial class CreatedDeviceResponse : Tausend.RelayServer.DeviceService.BaseResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStates", Namespace="http://schemas.datacontract.org/2004/07/Tausend.Core.Enums")]
    public enum ResponseStates : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BUSSINESS_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAUTHORIZED = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_DATA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_FOUND = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/Tausend.Backend.Models")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastConnection {
            get {
                return this.LastConnectionField;
            }
            set {
                if ((this.LastConnectionField.Equals(value) != true)) {
                    this.LastConnectionField = value;
                    this.RaisePropertyChanged("LastConnection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Port {
            get {
                return this.PortField;
            }
            set {
                if ((object.ReferenceEquals(this.PortField, value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Tausend.Wearelomo.com", ConfigurationName="DeviceService.DeviceService")]
    public interface DeviceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/CreateDevice", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/CreateDeviceResponse")]
        Tausend.RelayServer.DeviceService.CreatedDeviceResponse CreateDevice(string accessToken, string description, string identifier, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/CreateDevice", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/CreateDeviceResponse")]
        System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.CreatedDeviceResponse> CreateDeviceAsync(string accessToken, string description, string identifier, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByIdentifier", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByIdentifierResponse")]
        Tausend.RelayServer.DeviceService.DeviceResponse GetDeviceByIdentifier(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByIdentifier", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByIdentifierResponse")]
        System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.DeviceResponse> GetDeviceByIdentifierAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByID", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByIDResponse")]
        Tausend.RelayServer.DeviceService.DeviceResponse GetDeviceByID(long deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByID", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/GetDeviceByIDResponse")]
        System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.DeviceResponse> GetDeviceByIDAsync(long deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/DeleteDevice", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/DeleteDeviceResponse")]
        Tausend.RelayServer.DeviceService.DeletedDeviceResponse DeleteDevice(long deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/DeleteDevice", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/DeleteDeviceResponse")]
        System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.DeletedDeviceResponse> DeleteDeviceAsync(long deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceConnectionParameters", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceConnectionParametersRespon" +
            "se")]
        Tausend.RelayServer.DeviceService.UpdateDeviceResponse UpdateDeviceConnectionParameters(long deviceId, string ip, string port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceConnectionParameters", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceConnectionParametersRespon" +
            "se")]
        System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.UpdateDeviceResponse> UpdateDeviceConnectionParametersAsync(long deviceId, string ip, string port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceLastConnection", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceLastConnectionResponse")]
        Tausend.RelayServer.DeviceService.UpdateDeviceResponse UpdateDeviceLastConnection(long deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceLastConnection", ReplyAction="http://Tausend.Wearelomo.com/DeviceService/UpdateDeviceLastConnectionResponse")]
        System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.UpdateDeviceResponse> UpdateDeviceLastConnectionAsync(long deviceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceServiceChannel : Tausend.RelayServer.DeviceService.DeviceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceServiceClient : System.ServiceModel.ClientBase<Tausend.RelayServer.DeviceService.DeviceService>, Tausend.RelayServer.DeviceService.DeviceService {
        
        public DeviceServiceClient() {
        }
        
        public DeviceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tausend.RelayServer.DeviceService.CreatedDeviceResponse CreateDevice(string accessToken, string description, string identifier, string pin) {
            return base.Channel.CreateDevice(accessToken, description, identifier, pin);
        }
        
        public System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.CreatedDeviceResponse> CreateDeviceAsync(string accessToken, string description, string identifier, string pin) {
            return base.Channel.CreateDeviceAsync(accessToken, description, identifier, pin);
        }
        
        public Tausend.RelayServer.DeviceService.DeviceResponse GetDeviceByIdentifier(string identifier) {
            return base.Channel.GetDeviceByIdentifier(identifier);
        }
        
        public System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.DeviceResponse> GetDeviceByIdentifierAsync(string identifier) {
            return base.Channel.GetDeviceByIdentifierAsync(identifier);
        }
        
        public Tausend.RelayServer.DeviceService.DeviceResponse GetDeviceByID(long deviceId) {
            return base.Channel.GetDeviceByID(deviceId);
        }
        
        public System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.DeviceResponse> GetDeviceByIDAsync(long deviceId) {
            return base.Channel.GetDeviceByIDAsync(deviceId);
        }
        
        public Tausend.RelayServer.DeviceService.DeletedDeviceResponse DeleteDevice(long deviceId) {
            return base.Channel.DeleteDevice(deviceId);
        }
        
        public System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.DeletedDeviceResponse> DeleteDeviceAsync(long deviceId) {
            return base.Channel.DeleteDeviceAsync(deviceId);
        }
        
        public Tausend.RelayServer.DeviceService.UpdateDeviceResponse UpdateDeviceConnectionParameters(long deviceId, string ip, string port) {
            return base.Channel.UpdateDeviceConnectionParameters(deviceId, ip, port);
        }
        
        public System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.UpdateDeviceResponse> UpdateDeviceConnectionParametersAsync(long deviceId, string ip, string port) {
            return base.Channel.UpdateDeviceConnectionParametersAsync(deviceId, ip, port);
        }
        
        public Tausend.RelayServer.DeviceService.UpdateDeviceResponse UpdateDeviceLastConnection(long deviceId) {
            return base.Channel.UpdateDeviceLastConnection(deviceId);
        }
        
        public System.Threading.Tasks.Task<Tausend.RelayServer.DeviceService.UpdateDeviceResponse> UpdateDeviceLastConnectionAsync(long deviceId) {
            return base.Channel.UpdateDeviceLastConnectionAsync(deviceId);
        }
    }
}
